# Generated by Django 3.2 on 2026-02-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [  
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('viewingrequest_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_date', models.DateField()),
                ('requested_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_view', to='property.property')),
               # ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_view', to='user.user')),
            ],
        ),       
    ]
