# Generated by Django 3.2 on 2026-02-18 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20260216_2014'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewingRequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewingrequest',
            name='property_id',
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing_requests', to='property.property'),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
