# Generated by Django 3.2 on 2026-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewingRequest', '0002_auto_20260218_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
