# Generated by Django 3.2 on 2026-02-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewingRequest', '0003_viewingrequest_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewingrequest',
            old_name='property',
            new_name='property_id',
        ),
    ]
