# Generated by Django 3.2 on 2026-02-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewingRequest', '0004_rename_property_viewingrequest_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewingrequest',
            name='message',
        ),
    ]
