# Generated by Django 3.2 on 2026-02-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewingRequest', '0005_remove_viewingrequest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewingrequest',
            name='status',
        ),
    ]
