# Generated by Django 3.2 on 2026-02-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageprop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageprop',
            old_name='property_id',
            new_name='property',
        ),
    ]
