# Generated by Django 3.2 on 2026-02-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('propertyimage_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(upload_to='')),
                ('display_order', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_img', to='property.property')),
            ],
        ),
    ]
