# Generated by Django 3.2 on 2026-02-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_offer', to='property.property')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_offer', to='user.user')),
            ],
        ),
    ]
