# Generated by Django 3.2 on 2026-03-05 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0002_auto_20260219_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=100, null=True)),
                ('tenant_email', models.CharField(max_length=150, null=True)),
                ('tenant_phone', models.BigIntegerField()),
                ('contract_startdate', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_contract', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_contract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
