# Generated by Django 3.2 on 2026-03-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housecontract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
