# Generated by Django 3.2 on 2026-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housecontract', '0002_rentcontract_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
