# Generated by Django 3.2 on 2026-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housecontract', '0004_alter_rentcontract_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='income_source',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
