# Generated by Django 3.2 on 2026-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housecontract', '0005_rentcontract_income_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='national_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
