# Generated by Django 3.2 on 2026-06-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housecontract', '0006_rentcontract_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='family_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
