# Generated by Django 3.2 on 2026-07-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20260219_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
