# Generated by Django 3.2 on 2026-07-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favourite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
