# Generated by Django 3.2 on 2026-07-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_property_favourite'),
        ('favourite', '0002_auto_20260707_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='property_id',
        ),
        migrations.AddField(
            model_name='favourite',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_fav', to='property.property'),
        ),
    ]
