# Generated by Django 3.2 on 2026-07-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0003_auto_20260707_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
